FROM node

WORKDIR /app

# Root dependencies
COPY package*.json ./
RUN npm install

# Chat service dependencies
COPY services/billing/package*.json ./services/billing/
RUN cd services/billing && npm install

# Copy source code
COPY services/billing ./services/billing
COPY shared ./shared

WORKDIR /app/services/billing

EXPOSE 8004

CMD ["npm", "start"]